### ISSUE TITLE
Unsupported encoding type 30

### ISSUE THREAD

**Issue by HumanKR** [jiru/kakaodecrypt#11]
잘 진행되다가 갑자기 뻗더라고요
복호화가 완료된건가요? 아니면 오류인가요?
```
Traceback (most recent call last):
  File "kakaodecrypt.py", line 20, in genSalt
    salt = prefixes[encType] + str(user_id)
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kakaodecrypt.py", line 215, in <module>
    KakaoDbDecrypt.run(args.db_file, enc_table, dec_table, enc_fields, args.p, args.u)
  File "kakaodecrypt.py", line 177, in run
    contents = KakaoDecrypt.decrypt(user_id, enc_type, contents)
  File "kakaodecrypt.py", line 92, in decrypt
    salt = KakaoDecrypt.genSalt(user_id, encType)
  File "kakaodecrypt.py", line 23, in genSalt
    raise ValueError('Unsupported encoding type %i' % encType)
ValueError: Unsupported encoding type 30

```

**Comment by jiru** [comment]
감사합니다! Please try with the latest HEAD, it should work now.
